api-version: "1.13"
authors: ["lokka30"]
description: "The Ultimate Virtual Economy Service Provider"
main: "io.github.arcaneplugins.polyconomy.plugin.bukkit.Polyconomy"
name: "Polyconomy"
version: "${project.version}"
website: "https://github.com/ArcanePlugins/Polyconomy/"
