#  _
# |_) _  |     _  _   _   _   _ _
# |  (_) | \/ (_ (_) | | (_) | | | \/
#          /                       /

primary-locale: "en_US"

storage:
  implementation: "yaml"

advanced:
  minimum-balance: 0

metadata:
  file-version: 1
  original:
    file-version: 1
    plugin-version: "${project.version}"