#  _
# |_) _  |     _  _   _   _   _ _
# |  (_) | \/ (_ (_) | | (_) | | | \/
#          /                       /

primary-currency: "dollar"
primary-locale: "en_US"

currencies:
  - currency: "dollar"
    enabled: true
    starting-balance: 50
    symbol: "$"
    display-name-singular: "Dollar"
    display-name-plural: "Dollars"
    amount-format: "#,##0.00"
    presentation-format: "%symbol%%amount%"
    conversion-rate: 1
    decimal:
      - "en_US": "."

  - currency: "token"
    enabled: true
    starting-balance: 0
    symbol: "T"
    display-name-singular: "Token"
    display-name-plural: "Tokens"
    amount-format: "#,##0.00"
    presentation-format: "%amount% %display-name%"
    conversion-rate: 100
    decimal:
      - "en_US": "."

storage:
  implementation: "Yaml"

advanced:
  important-plugin-recommendations: false
  minimum-balance: 0
  signed-balances: true

metadata:
  file-version: 1
  original:
    file-version: 1
    plugin-version: "${project.version}"