#  _
# |_) _  |     _  _   _   _   _ _
# |  (_) | \/ (_ (_) | | (_) | | | \/
#          /                       /

primary-currency: "dollar"
primary-locale: "en_US"

currencies:
  - currency: "dollar"
    enabled: true
    starting-balance: 50
    symbol: "$"
    amount-format: "#,##0.00"
    presentation-format: "%symbol%%amount%"
    conversion-rate: 1
    display-name:
      - locale: "en_US"
        singular-value: "Dollar"
        plural-value: "Dollars"
    decimal:
      - locale: "en_US"
        value: "."

  - currency: "token"
    enabled: false
    starting-balance: 0
    symbol: "T"
    amount-format: "#,##0.00"
    presentation-format: "%amount% %display-name%"
    conversion-rate: 100
    display-name:
      - locale: "en_US"
        singular-value: "Token"
        plural-value: "Tokens"
    decimal:
      - locale: "en_US"
        value: "."

storage:
  implementation: "Yaml"

advanced:
  important-plugin-recommendations: false
  minimum-balance: 0
  signed-balances: true

metadata:
  file-version: 1
  original:
    file-version: 1
    plugin-version: "${project.version}"